### ISSUE TITLE
Change the value of AuthnCacheContext? 

### ISSUE THREAD

**Issue by HCHCHH** [ManageIQ/httpd_configmap_generator#42]
Thanks for providing the container! I have a question about one httpd config:`AuthnCacheContext`.
It seems the [official document](https://httpd.apache.org/docs/current/mod/mod_authn_socache.html#authncachecontext) recommends to change the default `directory`, which is conservative and not optimal. **A better policy is to name the `AuthnCacheContext` for the password provider: for example a htpasswd file or database table.**

Maybe it's better to set that to specify a context string for use in the cache keyin the comfig file? Thanks.

**Comment by mfeifer** [comment]
@carbonin

**Comment by carbonin** [comment]
Closing this for the same reason as https://github.com/ManageIQ/container-httpd/issues/40. It's spam.

**Comment by carbonin** [comment]
Ugh, damn, don't have permissions to close issues here, @abellotti whenever you get a chance.

**Comment by abellotti** [comment]
Thanks @carbonin for finding these bot triggered issues.
