### ISSUE TITLE
Question about changing EnableSendfile to On?

### ISSUE THREAD

**Issue by hh-project-config** [ManageIQ/httpd_configmap_generator#43]
Thanks for providing the container! 
I am doing a research aiming at finding issues in configuration files. After pulling the image we notice that `EnableSendfile` is set to `on` in `/etc/httpd/conf/httpd.conf`, whose default is `Off`. 

However, the HttpD [official document](https://httpd.apache.org/docs/2.4/mod/core.html#enablesendfile) recommends to set `EnableSendfile` to `Off` to avoid operational problems when:
* Some platforms may have broken sendfile support that the build system did not detect, especially if the binaries were built on another box and moved to such a machine with broken sendfile support.
* On Linux the use of sendfile triggers TCP-checksum offloading bugs on certain networking cards when using IPv6.
* On Linux on Itanium, sendfile may be unable to handle files over 2GB in size.
* With a network-mounted DocumentRoot (e.g., NFS, SMB, CIFS, FUSE), the kernel may be unable to serve the network file through its own cache.

Shall we set `EnableSendfile` back to `off` as default?

**Comment by mfeifer** [comment]
cc @carbonin

**Comment by carbonin** [comment]
This is the default value of `EnableSendfile` in our distribution of httpd (specifically this one http://mirror.centos.org/centos/7/os/x86_64/Packages/httpd-2.4.6-90.el7.centos.x86_64.rpm) so I'd like to not change it given that we are not currently overriding it.

Also I think this was just a bot account that went around spamming repos a while back. Not exactly a helpful issue.
