### ISSUE TITLE
docker build is failing with "/bin/sh: gem: command not found" error

### ISSUE THREAD

**Issue by seth-priya** [ManageIQ/httpd_configmap_generator#46]
Steps
git clone https://github.com/ManageIQ/httpd_configmap_generator
cd httpd_configmap_generator
docker build . -t manageiq/httpd_configmap_generator:latest

Error
Step 6/6 : RUN gem install --no-ri --no-rdoc --no-document httpd_configmap_generator
 ---> Running in 3e8dd6007819
/bin/sh: gem: command not found
The command '/bin/sh -c gem install --no-ri --no-rdoc --no-document httpd_configmap_generator' returned a non-zero code: 127

Note
This fails on x86_64 and ppc64le alike

Proposed solution
Install ruby-devel in the image

**Comment by jvlcek** [comment]
@simaishi Could this be a build issue with the httpd_configmap_generator?

**Comment by simaishi** [comment]
Looks like it's the change made to the base image (httpd and httpd-init split) that's causing the failure. I assume we should be using httpd-init now?  cc @Fryguy

**Comment by Fryguy** [comment]
Not sure...I don't really understand what this image needs out of the httpd image.

**Comment by simaishi** [comment]
I don't either...  so @jvlcek, if all those extra auth related packages are needed (https://github.com/ManageIQ/container-httpd-init/blob/master/Dockerfile), we can switch from httpd to httpd-init base image. Otherwise, we can install ruby.

**Comment by abellotti** [comment]
we do need all those other packages as the config map generator can invoke ipa client, or saml config tools, etc.   going from httpd to httpd-init will do the trick.

**Comment by simaishi** [comment]
Thanks @abellotti.  Opened https://github.com/ManageIQ/httpd_configmap_generator/pull/47
