### ISSUE TITLE
need to switch to Optimist

### ISSUE THREAD

**Issue by abellotti** [ManageIQ/httpd_configmap_generator#48]
trollop renamed and will no longer be supported.

**Comment by simaishi** [comment]
This was fixed in https://github.com/ManageIQ/httpd_configmap_generator/pull/34, but we just haven't released a new version of httpd_configmap_generator gem with the fix.  @Fryguy will be releasing a new version.

**Comment by abellotti** [comment]
thanks, that came even after the OIDC, and the error I am seeing is causing (use Optimist) is causing the awsome_spawn to exit.
